### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Arinerron** [liam4/tlnccuwagnf#1]
I'm looking forward to it. :package:

**Comment by towerofnix** [comment]
I'll do this at some point :P

There's thirty percent decent documentation in `lib.js` for the general library of things that needs to be used by like everything related to the language.

**Comment by towerofnix** [comment]
Kind of started here: https://github.com/liam4/tlnccuwagnf/blob/7157b92eab9f94b2f76adb815152804125391535/docs/Environments.md

**Comment by bates64** [comment]
We should probably start this soon - can we do it in GitHub Wikis @liam4?

**Comment by towerofnix** [comment]
Sure.
