### ISSUE TITLE
Why is everything in underscore_case?

### ISSUE THREAD

**Issue by bates64** [liam4/tlnccuwagnf#12]
userscore_case < UpperCamelCase < lowerCamelCase < dash-case

I like dash-case, because Tulun supports that.
**Hell, maybe we could implement _all the cases_!** 📦 
Thoughts?

**Comment by plastpappa** [comment]
why dash-case ?????? :-1:
edit: I vote for lowerCamelCase

**Comment by bates64** [comment]
> I like dash-case, because Tulun supports that.

Tulun supports pretty much **any character in variables**, so dash-case makes more sense than underscore_case for example because you don't have to hold shift all the time ;)

Also lowerCamelCase is cool but dash-case is much more fancy & unique. Oh, and it gets _really_ annoying after a while havingToCapitalizeEveryWord rather-than-just-doing-this.

@liam4 is it possible to have spaces in variable names? Because that would be verrrrry fun.

**Comment by towerofnix** [comment]
> Tulun supports pretty much any character in variables, so dash-case makes more sense than underscore_case for example because you don't have to hold shift all the time ;)

Yep! Except for the characters defined in the [`SPECIAL_CHARACTERS`](https://github.com/liam4/tlnccuwagnf/blob/master/src/constants.js#L19-L20) constant. I think.

> liam4 is it possible to have spaces in variable names? Because that would be verrrrry fun.

So spaces but not new lines? That'd be interesting :P

> Also lowerCamelCase is cool but dash-case is much more fancy & unique. Oh, and it gets really annoying after a while havingToCapitalizeEveryWord rather-than-just-doing-this.

I kind of like this, yeah.

**Comment by bates64** [comment]
Ha @kvackkvack ^

**Comment by plastpappa** [comment]
Why does no one ever agree with me on these issues? :P

**Comment by bates64** [comment]
So... dash-case? @liam4
