### ISSUE TITLE
Why `fn() {}`?

### ISSUE THREAD

**Issue by bates64** [liam4/tlnccuwagnf#13]
Why do we use

```
foo => fn(bar, baz) {
  # code #
}
```

rather than, for example

```
foo => (bar, baz) {
  # this is shorter! #
}
```

It's something I've been thinking about it and calling `fn` and then **passing variable definitions**...  it just seems to me like calling a function to create one seems a bit dodgey - it doesn't do what is expected.

**Comment by towerofnix** [comment]
`fn(args) {code}` seems a bit more explicit, but there are lots of times when I want to use `fn` as a parameter or variable.. _discussion needed!_ :P

I get it looks kind of like a function call. Hmm..

**Comment by bates64** [comment]
I have two ideas:

```
# 1
foo => (bar, baz) {
  # code code code #
}

# 2
foo => {
  (bar, baz) # hell if we can; ommit the brackets alltogether!
  # code code code #
}
```

Thoughts?

**Comment by towerofnix** [comment]
I prefer #<b></b>1 there.

**Comment by bates64** [comment]
Also I think _typed arguments_ should exist, builtin? For example:

```
foo => (bar@str) {
  print('yay')
}

foo(123) # foo(...): Argument 1 must be a string
```

**Comment by towerofnix** [comment]
> Also I think typed arguments should exist, builtin?

[I kind of dislike using static typing..](https://youtu.be/i4Hic0O5JLk?t=29)

If you need a string, change the input to a string. (Wait, we don't have a function for that? Oops..) If you _really_ need some fancy prototype thingy, check if it's of that class manually -- that's how I do it..

``` js
if (!(x instanceof FancyClass)) {
  throw new Error('Argument must be instance of FancyClass');
}
```

EDIT: Plus static typing belongs in a different issue!

**Comment by bates64** [comment]
I guess so :)
Although then we need some sort of `type()` function in Tulun!

**Comment by towerofnix** [comment]
Apparently people like this.

``` python
foo => (bar): *(bar, 2);
baz => (bar) { return(*(bar, 3)); };
```

**Comment by bates64** [comment]
And also this @liam4.

``` python
# single argument, ommit brackets (may be hard to implement?) #
foo => bar {...};

# no arguments, ommit brackets altogether #
foo => {...};
```

**Comment by towerofnix** [comment]
> single argument, ommit brackets (may be hard to implement?)

Probably not hard to implement. Not sure I like it though.

> no arguments, ommit brackets altogether

Oops, yeah, that too.

**Comment by bates64** [comment]
> Probably not hard to implement. Not sure I like it though.

Same here. Just implement the others first? :package:
