### ISSUE TITLE
Semicolon or newline shouldn't be required before EOF

### ISSUE THREAD

**Issue by towerofnix** [liam4/tlnccuwagnf#16]
At the moment you need to have a semicolon or newline before the EOF of a program/script:

This works:

```
print("Hello!");[EOF]
```

This works:

```
print("Hello!")
[EOF]
```

But this doesn't work:

```
print("Hello!")[EOF]
```

Unfortunately the changes in https://github.com/liam4/tlnccuwagnf/commit/15eff2a948125a245100639e4c0bdd26f3d17387 caused an ambiguity problem when a script ended with a newline just before the EOF.

**Comment by bates64** [comment]
For now, why not just append `\n` to the input?

**Comment by towerofnix** [comment]
Haha that would work.

**Comment by towerofnix** [comment]
AHA! I fixed it in my (local) `tests` branch. I'll try to stick the changes in master. No need to modify the input code!

Basically it's because `_` and `CommandSeparator` can appear beside each other, and both can make `\n`, making it ambiguous as to whether a `\n` is `_` or `CommandSeparator`.

**Comment by towerofnix** [comment]
FYI whitespace is broken, please delay pulling for now <3

**Comment by towerofnix** [comment]
Rolled back to 835c9d554eaba69eb54fdf7dad95ecee10c4116d (i.e. #17)
