### ISSUE TITLE
Everything breaks without semicolons

### ISSUE THREAD

**Issue by towerofnix** [liam4/tlnccuwagnf#2]
Should semicolons be optional? I'm not sure, but if not, it needs to be more clear that EVERY COMMAND MUST BE ENDED BY A SEMICOLON.

**Comment by plastpappa** [comment]
I don't mind semicolons being required, personally. I don't think it really matters too much, to be honest. :P

**Comment by bates64** [comment]
oppppppppppppppppptional pls

**Comment by towerofnix** [comment]
I think I can basically change

```
CommandSeparator -> ";"
```

to

```
CommandSeparator -> ";" | "\n"
```

and that should make them optional?

**Comment by bates64** [comment]
Should do :package:

**Comment by towerofnix** [comment]
_does now_

**Comment by plastpappa** [comment]
Depending on how the grammar is written, it feels like that might just throw a bunch of commandseperators everywhere there is a new line, which probably works but feels like the tokens might get a bit ugly. (I can't think of a better way to do it though :P)

**Comment by bates64** [comment]
@liam4 should this issue be closed?

**Comment by towerofnix** [comment]
This hasn't been fixed yet :/ I tried that change a while ago but it didn't fix it. I'll look into it more soon :P

EDIT: semicolons are bad
