### ISSUE TITLE
Alex why

### ISSUE THREAD

**Issue by towerofnix** [liam4/tlnccuwagnf#22]
YOU REPLACED ALL VAR WITH LET

like come on, that'll take me ages to fix :P.

(I guess I could replace all let w/ var)

``` js
export function evaluateExpression(expression, letiables) {
```

@nanalan

**Comment by towerofnix** [comment]
Fixing this in the `environment` branch

**Comment by nanalan** [comment]
Why?

**Comment by bates64** [comment]
Oops.
