### ISSUE TITLE
Development branch?

### ISSUE THREAD

**Issue by Arinerron** [liam4/tlnccuwagnf#26]
Why not have a `development` branch so people can download almost-stable releases (Edit: **As ZIP, not via npm.**) from `master` while you can work on the `development` branch safely without breaking people's downloads, and merge the branches every-so-often?

**Comment by towerofnix** [comment]
So have something like this?

```
master
|
|- development
   |
   |- feature1
   |- feature2
   |- feature3
```

I'm +1 for that :P

**Comment by bates64** [comment]
:-1: 
npm does that automagically:
`npm publish --tag beta`
`npm install ... --tag beta`

**Comment by bates64** [comment]
@Arinerron, if you install using npm then just install the stable versions.

**Comment by towerofnix** [comment]
That's a good point..

**Comment by Arinerron** [comment]
@nanalan @liam4 No, not npm. I'm talking about downloading as ZIP.

**Comment by bates64** [comment]
@Arinerron Those are called github releases, silly.
Also **why aren't you using npm**??

**Comment by Arinerron** [comment]
@nanalan Alright, GitHub Releases.

I am using npm (see pull request and issue about it). I am also using the zip download though to mess around with the source code easily.

**Comment by bates64** [comment]
Ah... if you want to mess with the source:

``` sh
git clone https://github.com/liam4/tlnccuwagnf.git tulun
cd tulun
npm install
npm link
```

And `tulun`, available globally, will be linked the **your** commandline version of tulun.
