### ISSUE TITLE
Make a REPL

### ISSUE THREAD

**Issue by Arinerron** [liam4/tlnccuwagnf#30]
I'm wondering if it is possible to create a console access for tulun. For example, Python and JavaScript have consoles in which you can type the code and have it parsed realtime.

**Comment by bates64** [comment]
I believe you mean a **REPL** (Read Eval Print Loop).
It's pretty hard to make but we can try? :package:

**Comment by plastpappa** [comment]
I almost completed one for PLT. Wasn't very hard. Maybe there's something very different for Tulun though?

**Comment by bates64** [comment]
Do you have the code anywhere?

**Comment by plastpappa** [comment]
I'll check... It'd have to be on my old computer still.

**Comment by plastpappa** [comment]
Can't find it. I'll try to write something similar but for this later today though... Got school now. :package:
