### ISSUE TITLE
cannot use some special characters (=, >, <) in functions

### ISSUE THREAD

**Issue by bates64** [liam4/tlnccuwagnf#31]
``` js
<> => 1;
loop({
  print(<>);
  <> -> +(<>, 1);
  ret => true;
  if(=(<>, 8), {
    ret -> false;
  });
  return(ret);
});
```

**Error: nearley: No possible parsings (@2: ' ').**

What happen?

**Comment by towerofnix** [comment]
This happen!

``` js
allExports.SPECIAL_CHARS = '(){}=>\'" .:;#'
```

Though this could be coded a little better, i.e. so that instead of making identifiers not able to contain `>`, make them not be able to be equal to `=>`...

**Comment by bates64** [comment]
Ah. Yeah, that'd help :package:

**Comment by towerofnix** [comment]
Oh, wow, there's already a `KEYWORDS` constant? I didn't remember making that! Haha yay. :tada:

**Comment by bates64** [comment]
@liam4 come to Gitter?
