### ISSUE TITLE
Language name ideas

### ISSUE THREAD

**Issue by towerofnix** [liam4/tlnccuwagnf#5]
Currently it's called nearley-test. @BookOwl couldn't have said this any better:

> You need to come up with better names :stuck_out_tongue_winking_eye:

Ideas?

PS: [this Wikipedia page](https://en.wikipedia.org/wiki/List_of_Intel_codenames) (see also [this video](https://www.youtube.com/watch?v=NRrgtUJnkIo&feature=youtu.be&t=4m43s)) (also [this Wikipedia page](https://en.wikipedia.org/wiki/List_of_computer_technology_code_names)) could be useful.

**Comment by towerofnix** [comment]
So far I've only got TLING: This Language Is Not Good. I don't think I'll use that one.

**Comment by BookOwl** [comment]
LIAM - Liam's Incredible Awesome prograM

**Comment by towerofnix** [comment]
LIAM - **L**IAM **i**s **am**azing

Recursive FTW :package:

**Comment by plastpappa** [comment]
APL - **A**nother **P**rogramming **L**anguage? (from the GitHub description)
LiamScript?
:package:

**Comment by towerofnix** [comment]
But then there's also [this](https://en.wikipedia.org/wiki/APL_%28programming_language%29).. Hmm..

**Comment by plastpappa** [comment]
LAPL - **L**iam's **A**nother **P**rogramming **L**anguage?

**Comment by towerofnix** [comment]
I'm not sure about using my name in the title :P

**Comment by bates64** [comment]
ARSL - A Really Silly Language?

**Comment by towerofnix** [comment]
ANSL - ANother Silly Language?

(PS there's also the option of non-abbreviation names, but if we can think of a _really good_ abbreviation that could also be nice)

**Comment by bates64** [comment]
YAPL - Yet Another Programming Language

**Comment by towerofnix** [comment]
But http://lambda-the-ultimate.org/node/3293 :(

**Comment by bates64** [comment]
;-;

**Comment by towerofnix** [comment]
AaCoJS, Almost a Copy of JavaScript. :package:

"aa-koh-JS"?

**Comment by bates64** [comment]
TINA - This is not an abbreviation? :package:

**Comment by plastpappa** [comment]
TLNCCUWAGNF - The Language Nobody Could Come Up With A Good Name For?

**Comment by towerofnix** [comment]
+9001 :P

Pronunciation?

**Comment by towerofnix** [comment]
TLNC-que-wag-NF?

That doesn't seem right :P

**Comment by bates64** [comment]
Tul-un-qweh-wag-nuf.

**Comment by towerofnix** [comment]
We should go with TLNCCUWAGNF for sure!

**Comment by towerofnix** [comment]
Going with TLNCCUWAGNF, objections can be given but they need to be good ones because I really like TLNCCUWAGNF :P

**Comment by towerofnix** [comment]
Tulun for short.
