### ISSUE TITLE
File extension name?

### ISSUE THREAD

**Issue by towerofnix** [liam4/tlnccuwagnf#6]
I'm going to go with `program.tul` for now, any other suggestions?

**Comment by bates64** [comment]
Maybe have the shortened _.tul_ **and** the longer _.tulun_?

**Comment by 109C** [comment]
How about `.ngn`, as in `No Good Name`?

**Comment by bates64** [comment]
@109C But what does that have to do with **tlnccuwagnf**? :package:

**Comment by towerofnix** [comment]
> Maybe have the shortened .tul **and** the longer .tulun?

Eh, I'm not sure I want multiple extensions :P

**Comment by 109C** [comment]
@GrannyCookies Nothing. I just couldn't come up with a good name for the extension.

**Comment by bates64** [comment]
We should stick with `.tul`, as now `use(...)` uses it internally.
Also `.tul` is a good extension.

**Comment by towerofnix** [comment]
> We should stick with .tul, as now use(...) uses it internally.

kek. It uses it internally _in your fork._

(But I'm going to merge that anyways)

But yes `tul` ftw :P
