### ISSUE TITLE
Grammar is ambigous

### ISSUE THREAD

**Issue by 109C** [liam4/tlnccuwagnf#7]

**Comment by towerofnix** [comment]
Comparing the trees with [this amazing tool](http://tlrobinson.net/projects/javascript-fun/jsondiff/) reveals that numbers (and booleans) can be parsed as variables - this _should_ be a fairly simple fix.

Thanks for reporting! I'll be sure to get into looking for more ambiguities (and fixing those that you've discovered!). I've set up a bit of code to warn about ambiguous syntax.

**Comment by towerofnix** [comment]
Alright, I fixed this in commits https://github.com/liam4/tlnccuwagnf/commit/2df352713feb6544ff54bec8c813905796149b7b and https://github.com/liam4/tlnccuwagnf/commit/702c7a831195177bcac55855f7e661894672dfeb! If you find any more ambiguities (the interpreter will warn you about any ambiguity issues) be sure to file another issue.
