### ISSUE TITLE
Unevaluated function parameters (syntax input wanted)

### ISSUE THREAD

**Issue by towerofnix** [liam4/tlnccuwagnf#9]
**Why?** To make better control structures:

```
# old #
x => 2;
while(fn() { return(lt(x, 8)) }, fn() {
  x -> +(x, 1);
  print(x);
});

# new #
x => 2;
while(lt(x, 8), fn() {
  x -> +(x, 1);
  print(x);
});
```

**How?** I'm not sure. I can easily implement it but I'm not sure what the syntax should be -- all I can think of right now is this:

```
while => fn(unevaluated condition, loop) { #...# };
```

That's really big and clunky but clearer than something like this:

```
while => fn(%condition, loop) { #...# };
```

Any suggestions?

**Comment by towerofnix** [comment]
ping @BookOwl, @kvackkvack

You guys should all have followed this repository! >:D I need your help!

**Comment by BookOwl** [comment]
Sorry, I was offline for the past few hours. I assume that you wouldn't use this feature that much, so `unevaluated name` is fine. If you want something smaller, how about `|name|`?

**Comment by towerofnix** [comment]
Implemented with `unevaluated name` in https://github.com/liam4/tlnccuwagnf/commit/473ad48a74f57f3654b071ae53330909e74d1dcb. Still kind of open to suggestions but I think I'll stick with that.

**Comment by plastpappa** [comment]
I don't like using unevaluated like that since there aren't any other statements implemented. :package: I'd prefer `|name|` like @BookOwl suggests.

**Comment by towerofnix** [comment]
Maybe `:name`, or `..name`? idk

> since there aren't any other statements implemented.

You mean we don't have any other English words implemented (like `var` or `change` or whatever)? If so +1 :P

**Comment by bates64** [comment]
how about `noEval(...)`? :package:

**Comment by plastpappa** [comment]
> how about noEval(...)? :package:

ew no how would that work? :P to make it actually unevaluated then, you'd have to make unEval() a special case which makes its arguments unevaluated in the first place, and it'd all be very confusing.  
I still like |name| the best. :P maybe noeval name, but it shouldn't be a function.

**Comment by 109C** [comment]
How about `'(lt(x, 8))`?

**Comment by towerofnix** [comment]
> How about '(lt(x, 8))?

Hold on, how does that work?

Keep in mind we're working on the syntax for unevaluated function parameters, i.e. what goes in the prototype/definition of the function:

```
this_is_a_fn => fn(insert unevaluated syntax here) {
  code code code
};
```

**Comment by bates64** [comment]
I like `|name|`, then.

**Comment by towerofnix** [comment]
We're going with `unevaluated arg-name`.
